#!/bin/bash
if [ "$USE_RELITE" == "" ]
then
  #/usr/bin/g++ "$@"
  /home/dvyukov/gcc-dehydra/installed/bin/g++ "$@"
else
  #echo RELITE: /home/dvyukov/gcc-dehydra/installed/bin/g++ -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DDYNAMIC_ANNOTATIONS_WANT_ATTRIBUTE_WEAK -DDYNAMIC_ANNOTATIONS_PREFIX=LLVM -fno-inline -fno-exceptions -fplugin=/home/dvyukov/tsan/gcc/plg/Debug/librelite.so -fplugin-arg-librelite-ignore="$RELITE_IGNORE" -include/home/dvyukov/tsan/gcc/plg/relite_rt.h "$@"
  /home/dvyukov/gcc-dehydra/installed/bin/g++ -DDYNAMIC_ANNOTATIONS_WANT_ATTRIBUTE_WEAK -DDYNAMIC_ANNOTATIONS_PREFIX=LLVM -fno-inline -fno-exceptions -fplugin=/home/dvyukov/tsan/gcc/plg/Debug/librelite.so -fplugin-arg-librelite-ignore="$RELITE_IGNORE" -include/home/dvyukov/tsan/gcc/plg/relite_rt.h "$@"
fi

