#!/bin/bash
if [ "$USE_RELITE" == "" ]
then
  #/usr/bin/g++ "$@"
  /home/dvyukov/gcc-dehydra/installed/bin/g++ "$@"
else
  #echo RELITE: /home/dvyukov/gcc-dehydra/installed/bin/g++ -DDYNAMIC_ANNOTATIONS_WANT_ATTRIBUTE_WEAK -DDYNAMIC_ANNOTATIONS_PREFIX=LLVM -fplugin=/home/dvyukov/tsan/gcc/plg/Debug/librelite.so -fplugin-arg-librelite-ignore="$RELITE_IGNORE" -include/home/dvyukov/tsan/gcc/plg/relite_rt.h "$@" -O1 -fno-inline -fno-optimize-sibling-calls -fno-exceptions
  /home/dvyukov/gcc-dehydra/installed/bin/g++ -DDYNAMIC_ANNOTATIONS_WANT_ATTRIBUTE_WEAK -DDYNAMIC_ANNOTATIONS_PREFIX=LLVM -fplugin=/home/dvyukov/tsan/gcc/plg/Debug/librelite.so -fplugin-arg-librelite-ignore="$RELITE_IGNORE" -include/home/dvyukov/tsan/gcc/plg/relite_rt.h "$@" -O1 -fno-inline -fno-optimize-sibling-calls -fno-exceptions
fi

