#!/bin/bash
if [ "$USE_RELITE" == "" ]
then
  /usr/bin/gcc "$@"
  #/home/dvyukov/gcc-dehydra/installed/bin/gcc "$@"
else
  /home/dvyukov/gcc-dehydra/installed/bin/gcc -DDYNAMIC_ANNOTATIONS_WANT_ATTRIBUTE_WEAK -DDYNAMIC_ANNOTATIONS_PREFIX=LLVM -fplugin=/home/dvyukov/tsan/gcc/plg/Debug/librelite.so -fplugin-arg-librelite-ignore="$RELITE_IGNORE" -include/home/dvyukov/tsan/gcc/plg/relite_rt.h $RELITE_GCC_ARGS "$@" -O1 -fno-inline -fno-optimize-sibling-calls -fno-exceptions
fi

