#!/bin/bash

wrap () {
  ARGS_MODIFIED+="--wrap=$1 "
}

undefined() {
  ARGS_MODIFIED+=""
}

if [ "$USE_RELITE" == "" ]
then
  echo /usr/bin/ld "$@"
  /usr/bin/ld "$@"
else
  GCCTSAN_GCC_PATH="/home/dvyukov/gcc-dehydra/installed"
  ARGS=""
  ARGS_MODIFIED=""
  INSERTED=""
  SHARED=""
  M32=""
  source /home/dvyukov/tsan/llvm/scripts/link_config.txt

  ARGS+=" -L$GCCTSAN_GCC_PATH/lib32"
  ARGS_MODIFIED+=" -L$GCCTSAN_GCC_PATH/lib32"

  #if [ "$GCCTSAN_BFD_LIB" == "" ]; then
  #  GCCTSAN_BFD_LIB="bfd"
  #fi
  
  until [ -z "$1" ]
  do
    if [ "$1" == "-shared" ]
    then
      SHARED="1"
    fi

    if [ "$1" == "elf_i386" ]
    then
      M32="1"
    fi

    if [ `expr substr "$1" 1 2` == "-l" ]
    then
      if [ "$INSERTED" == "" ]
      then
        INSERTED="1"
	if [ "$M32" == "1" ]
	then
		ARGS_MODIFIED+=" /home/dvyukov/tsan/llvm/tsan_rtl/tsan_rtl32.a -lrt -lpthread"
	else
        	ARGS_MODIFIED+=" /home/dvyukov/tsan/llvm/tsan_rtl/tsan_rtl64.a -lrt -lbfd -lpthread"
	fi
      fi
    fi
    ARGS+=" $1"
    ARGS_MODIFIED+=" $1"
    shift
  done

  if [ "$SHARED" == "1" ]
  then
    echo RELITE_SHARED: /usr/bin/ld $ARGS
    /usr/bin/ld $ARGS
  else
    echo RELITE: /usr/bin/ld $ARGS_MODIFIED
    /usr/bin/ld $ARGS_MODIFIED
  fi
fi




