#!/bin/bash

wrap () {
  ARGS+="--wrap=$1 "
}

undefined() {
  ARGS+=""
}

if [ "$USE_RELITE" == "" ]
then
  /usr/bin/ld "$@"
else
  ARGS=""
  INSERTED=""
  source /home/dvyukov/tsan/llvm/scripts/link_config.txt

  until [ -z "$1" ]
  do
    if [ `expr substr "$1" 1 2` == "-l" ]
    then
      if [ "$INSERTED" == "" ]
      then
        INSERTED="1"
        ARGS+=" /home/dvyukov/tsan/llvm/tsan_rtl/tsan_rtl64.a -lbfd"
      fi
    fi
    ARGS+=" $1"
    shift
  done

  echo RELITE: /usr/bin/ld $ARGS
  /usr/bin/ld $ARGS
fi


