#!/bin/bash
#
# A wrapper for g++ that detects whether g++ is used as a compiler or linker
# and either instruments the compiled source files or calls ./ld to link
# the object files.

SCRIPT_ROOT=`dirname $0`
source "$SCRIPT_ROOT/common.sh"
COMPILER="$LLVM_GCC"
FALLBACK_COMPILER="/usr/bin/gcc"
source "$SCRIPT_ROOT/gcc_common.sh"
