#!/bin/bash
#
# A g++ wrapper that links the instrumented object files together with
# ThreadSanitizer RTL. It also puts together all the debug information
# generated by opt.

set -x
SCRIPT_ROOT=`dirname $0`

source "$SCRIPT_ROOT/common.sh"


SRC=$1
FNAME=`echo $SRC | sed 's/\.[^.]*$//'`
SRC_BIT="$FNAME.ll"
SRC_INSTR="$FNAME-instr.ll"
SRC_ASM="$FNAME.S"
SRC_OBJ="$FNAME.o"
SRC_EXE="$FNAME"

ARGS=
DBG_FILES=

until [ -z "$1" ]
do
  if [ `expr match "$1" "-o"` -gt 0 ]
  then
    if [ "$1" == "-o" ]
    then
      # "-o exename" -- 2 arguments
      shift
      SRC_EXE="$1"
    else
      # "-oexename" -- 1 argument
      SRC_EXE=${1:2}
    fi
  elif [ `expr match "$1" "-m64"` -gt 0 ]
  then
    # pass
    echo "Dropped arg: $1"
  elif [ `expr match "$1" ".*\.[ao]"` -gt 0 ]
  then
    DBG_FILES="$DBG_FILES $1.dbg"
    ARGS="$ARGS $1"
  else
    ARGS="$ARGS $1"
  fi
  shift
done
SRC_DBG="$SRC_EXE.dbg"

source "$SCRIPT_ROOT/link_config.sh"

INST_MODE=-offline
INST_MODE=-online
CXXFLAGS=

LOG=instrumentation.log

# Link with the mops_impl.o
$LD -g $ARGS $LDFLAGS $TSAN_RTL -o $SRC_EXE || exit 1
$LINK_DBG $DBG_FILES -o $SRC_DBG
